server:
  port: 8002
spring:
  application:
    name: my-order
  config:
    import: nacos:my-order.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: abc@1234
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: abc@1234
