server:
  port: 8001
spring:
  application:
    name: my-product
  config:
    import: nacos:my-product.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: abc@1234
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: abc@1234

feign:
  sentinel:
    enabled: true